
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#  activemq:
#    user: admin
#    password: admin
#    broker-url: tcp://127.0.0.1:61616
#  jms:
#    topic-name: topic
#    queue-name: queue
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl